### ISSUE TITLE
UI Freezes

### ISSUE THREAD

**Issue by AdamUllmann** [ChicoState/DAWdle#11]
We currently have a problem with our UI completely freezing. When this happens, the audio playback and user inputs are completely accurate, but you can't visually see what you are doing in the program. This was first observed at around commit 92c0e7c. The problem might have existed before this commit, but it was impossible to test before that point.

**Comment by Tabris05** [comment]
Yeah I've observed this as well. Not certain it'd fix the problem, but I would be curious to see if this issue persists if we move all the audio stream code to its own thread.

**Comment by Tabris05** [comment]
Is this still happening for anyone? Can't reproduce it on the current build on my machine

**Comment by Drillgon200** [comment]
It definitely is still happening.
